# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --add-opens=java.base/java.lang=ALL-UNNAMED
org.gradle.configuration-cache=true
kotlin.code.style=official

# Disable automatic download/provisioning of Gradle JVM toolchains
org.gradle.jvm.toolchain.installtoolchains=false
org.gradle.java.installtoolchains=false

# Disable AGP built-in Kotlin to allow org.jetbrains.kotlin.android plugin
android.experimental.builtInKotlin=false
